name: CI Main Int

on:
  push:
    branches: [ main ]

  workflow_dispatch:

concurrency: 
  group: main-int
  cancel-in-progress: false

env:
  STAGE: int

jobs:

  unit-test:
    runs-on: ubuntu-latest

    name: Unit tests

    steps:
      - uses: bahmutov/npm-install@v1.8.14

      - name: Run unit tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest

    name: Deploy Int

    needs: [ unit-test ]

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Run Serverless Stack deploy
        run: npm run deploy -- --stage ${STAGE}
