name: CI Main Int

on:
  push:
    branches: [ main ]

  workflow_dispatch:

concurrency: 
  group: main-int
  cancel-in-progress: false

env:
  STAGE: int
  AWS_DEFAULT_REGION: eu-wast-1

jobs:

  unit-test:
    runs-on: ubuntu-latest

    name: Unit tests

    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1.8.14

      - name: Run unit tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest

    name: Deploy Int

    needs: [ unit-test ]

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::198805281865:role/GitHubFederatedRole
          role-session-name: samplerolesession
          aws-region: ${{env.AWS_DEFAULT_REGION}}

      - name: Run Serverless Stack deploy
        run: npm run deploy -- --stage ${STAGE}
